"""Added Post model

Revision ID: 1c77b387c51d
Revises: a7a923f4f20b
Create Date: 2024-10-16 22:14:31.454243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c77b387c51d'
down_revision = 'a7a923f4f20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=280),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key('fk_post_author_id', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.alter_column('content',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.drop_column('author_id')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
